dist: bionic
sudo: required

services:
  - docker

before_install:
  - gem install scss_lint
  - cp -r ./src/gtk-3.20/ ./gtk320lint
  - sed -ie 's/%[A-Z0-9_]\+%/123456/g' ./gtk320lint/scss/_global.scss
  - scss-lint ./gtk320lint/

install:
  - docker image build ./ -t oomox-gtk-theme

before_script:
  - docker run --entrypoint ./test/shellcheck.sh oomox-gtk-theme:latest

script:
  - docker run --entrypoint ./test/all_tests.sh oomox-gtk-theme:latest
